name: ✨ 새로운 기능
description: 새로운 기능을 추가할 때 사용합니다.
title: "[Feature] <제목>"
labels: ["Feature"]
body:
- type: textarea
  attributes:
    label: 이슈의 SubTask들을 알려주세요.
    description: 해당 내용의 SubTask를 나열해주세요.
    placeholder: - [ ] subtask 1
  validations:
    required: true
